# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 11:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=5500)),
                ('commentid', models.CharField(max_length=5500)),
                ('comment', models.CharField(max_length=5500)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=5500)),
                ('post', models.CharField(max_length=5500, validators=[django.core.validators.MinLengthValidator(1)])),
                ('author', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5500)),
                ('email', models.CharField(max_length=5500)),
                ('password', models.CharField(max_length=5500)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
