# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171008_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.CharField(max_length=5500),
        ),
    ]
